version: '3.4'
name: {{{{appKey}}}}
services:
  app:
    container_name: {{{{appKey}}}}-app
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - ${APP_PORT:-3000}:${APP_PORT:-3000}
      - ${WEBSOCKET_PORT:-24678}:${WEBSOCKET_PORT:-24678}
    volumes:
      - ./:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{{{appKey}}}}.tls=true
      - traefik.http.routers.{{{{appKey}}}}.rule=Host("{{{{appKey}}}}.docker.localhost")
    networks:
      - applications
networks:
  applications:
    external: true